import { useState } from "react";
import { useTranslation } from "react-i18next";
import { SITE } from "@/config/site";

type Variant = "portrait" | "laptop";

/**
 * Photographs of Aish: the city-window portrait (square) or the laptop shot
 * (4:5). Generated by scripts/prepare-brand-assets.mjs. If a file is absent
 * the figure is removed rather than showing a broken image or a placeholder.
 */
export function Portrait({ variant = "portrait", size = 280 }: { variant?: Variant; size?: number }) {
  const { t } = useTranslation();
  const [failed, setFailed] = useState(false);
  if (failed) return null;
  const img = variant === "laptop" ? SITE.laptop : SITE.portrait;
  const alt = variant === "laptop" ? t("about.laptopAlt") : t("about.portraitAlt");
  const ratio = img.height / img.width;
  const sizes = `(max-width: 640px) 70vw, ${size}px`;
  const swap = (src: string, ext: string) => src.replace(/\.jpg$/, `.${ext}`);
  return (
    <figure className="metal-card relative overflow-hidden rounded-lg p-2" style={{ maxWidth: size }}>
      <picture>
        <source type="image/avif" srcSet={`${swap(img.srcSmall, "avif")} ${img.width / 2}w, ${swap(img.src, "avif")} ${img.width}w`} sizes={sizes} />
        <source type="image/webp" srcSet={`${swap(img.srcSmall, "webp")} ${img.width / 2}w, ${swap(img.src, "webp")} ${img.width}w`} sizes={sizes} />
        <img
          src={img.src}
          srcSet={`${img.srcSmall} ${img.width / 2}w, ${img.src} ${img.width}w`}
          sizes={sizes}
          alt={alt}
          width={img.width}
          height={img.height}
          loading="lazy"
          decoding="async"
          className="w-full rounded-[4px] object-cover"
          style={{ aspectRatio: `1 / ${ratio}` }}
          onError={() => setFailed(true)}
        />
      </picture>
      <span aria-hidden="true" className="gold-bar absolute inset-x-2 bottom-2 h-[2px] opacity-80" />
    </figure>
  );
}
